### ISSUE TITLE
Get picture from new location

### ISSUE THREAD

**Issue by pmoosh** [suhasdeshpande/hoverboard#11]

**Comment by twhetzel** [comment]
@pmoosh do you want a new picture or use the one linked to in issue #3

**Comment by pmoosh** [comment]
New picture from new location

**Comment by twhetzel** [comment]
Ok, keep in mind the other photo was too busy to clearly display the text even with making the image opaque and the text bold.

**Comment by pmoosh** [comment]
Yeah we can use the image Seattle uses

**Comment by pmoosh** [comment]
Closing this with new pull request

https://github.com/suhasdeshpande/hoverboard/pull/17
